run:
  deadline: 120s
linters:
  enable:
    - govet
    - golint
    - ineffassign
    - goconst
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - scopelint
    - stylecheck
    - unconvert
    - gocritic
    - errcheck
  disable-all: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - bodyclose
        - unconvert
        - gocritic
        - errcheck
linters-settings:
  errcheck:
    check-type-assertions: true
  goimports:
    local-prefixes: github.com/oauth2-proxy/oauth2-proxy
