http:
  routers:
    a-service-route-1:
      rule: "Host(`httpbin.localtest.me`)"
      service: a-service-backend
      middlewares:
        - oauth-auth-redirect # redirects all unauthenticated to oauth2 signin
    a-service-route-2:
      rule: "Host(`httpbin.localtest.me`) && PathPrefix(`/no-auto-redirect`)"
      service: a-service-backend
      middlewares:
        - oauth-auth-wo-redirect # unauthenticated session will return a 401
    services-oauth2-route:
      rule: "Host(`httpbin.localtest.me`) && PathPrefix(`/oauth2/`)"
      middlewares:
        - auth-headers
      service: oauth-backend
    oauth2-proxy-route:
      rule: "Host(`oauth2-proxy.localtest.me`)"
      middlewares:
        - auth-headers
      service: oauth-backend
    keycloak:
      rule: "Host(`keycloak.localtest.me`)"
      service: keycloak-back

  services:
    a-service-backend:
      loadBalancer:
        servers:
          - url: http://httpbin
    oauth-backend:
      loadBalancer:
        servers:
          - url: http://oauth2-proxy:4180

    keycloak-back:
      loadBalancer:
        servers:
          - url: http://keycloak:9080

  middlewares:
    auth-headers:
      headers:
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
    oauth-auth-redirect:
      forwardAuth:
        address: http://oauth2-proxy:4180
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
    oauth-auth-wo-redirect:
      forwardAuth:
        address: http://oauth2-proxy:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
